// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrabajoPracticoP3.DBContext;

#nullable disable

namespace TrabajoPracticoP3.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("OrderProduct", b =>
                {
                    b.Property<int>("OrdersId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrdersId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("OrderProduct", (string)null);
                });

            modelBuilder.Entity("TrabajoPracticoP3.Data.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Payment")
                        .HasColumnType("TEXT");

                    b.Property<string>("TotalPrize")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("TrabajoPracticoP3.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pizza de Muzzarella",
                            Price = "3000"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pizza de Jamon",
                            Price = "3500"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Pizza de Pepperoni",
                            Price = "4000"
                        });
                });

            modelBuilder.Entity("TrabajoPracticoP3.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("SurName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasDiscriminator<string>("UserType").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TrabajoPracticoP3.Data.Entities.Admin", b =>
                {
                    b.HasBaseType("TrabajoPracticoP3.Data.Entities.User");

                    b.HasDiscriminator().HasValue("Admin");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "JuanPerez@gmail.com",
                            Name = "Juan",
                            Password = "987654",
                            SurName = "Perez",
                            UserName = "JuancitoPerez",
                            UserType = "Admin"
                        });
                });

            modelBuilder.Entity("TrabajoPracticoP3.Data.Entities.Client", b =>
                {
                    b.HasBaseType("TrabajoPracticoP3.Data.Entities.User");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Client");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Email = "Erne22@gmail.com",
                            Name = "Ernesto",
                            Password = "123321",
                            SurName = "Gutierrez",
                            UserName = "ElGuason21",
                            UserType = "Client",
                            Address = "Pellegrini 211",
                            PhoneNumber = "3415123212"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Seba25@gmail.com",
                            Name = "Sebastuan",
                            Password = "554466",
                            SurName = "Gonzalez",
                            UserName = "Batman21",
                            UserType = "Client",
                            Address = "Mendoza 211",
                            PhoneNumber = "3415123333"
                        });
                });

            modelBuilder.Entity("OrderProduct", b =>
                {
                    b.HasOne("TrabajoPracticoP3.Data.Entities.Order", null)
                        .WithMany()
                        .HasForeignKey("OrdersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrabajoPracticoP3.Data.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrabajoPracticoP3.Data.Entities.Order", b =>
                {
                    b.HasOne("TrabajoPracticoP3.Data.Entities.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("TrabajoPracticoP3.Data.Entities.Client", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
